services:
  - type: web
    name: cookbook
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: apache2-foreground
    dependencies:
      - name: cookbook
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/main
      - key: PHP_MEMORY_LIMIT
        value: 256M
      - key: DB_HOST
        fromDatabase:
          name: cookbook
          property: host
      - key: DB_USER
        fromDatabase:
          name: cookbook
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cookbook
          property: password
      - key: DB_NAME
        fromDatabase:
          name: cookbook
          property: database
    healthCheckPath: /main/index.php
    autoDeploy: true

  - type: mysql
    name: cookbook-mysql
    region: oregon
    plan: free
    ipAllowList: []

databases:
  - name: cookbook-db
    databaseName: cookbook
    plan: free
    postgresSqlVersion: "14" 