services:
  - type: web
    name: cookbook
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: apache2-foreground
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/main
      - key: PHP_MEMORY_LIMIT
        value: 256M
      - key: DB_HOST
        fromService:
          type: mysql
          name: cookbook-mysql
          property: host
      - key: DB_USER
        fromService:
          type: mysql
          name: cookbook-mysql
          property: user
      - key: DB_PASSWORD
        fromService:
          type: mysql
          name: cookbook-mysql
          property: password
      - key: DB_NAME
        fromService:
          type: mysql
          name: cookbook-mysql
          property: database
    healthCheckPath: /main/index.php
    autoDeploy: true

  - type: mysql
    name: cookbook-mysql
    region: oregon
    plan: free
    ipAllowList: []

databases:
  - name: cookbook-db
    databaseName: cookBook
    user: cookbook_user
    plan: free 