services:
  - type: web
    name: cookbook
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: apache2-foreground
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/main
      - key: PHP_MEMORY_LIMIT
        value: 256M
      - key: MYSQL_HOST
        fromService:
          type: mysql
          name: cookbook-db
          property: host
      - key: MYSQL_USER
        fromService:
          type: mysql
          name: cookbook-db
          property: user
      - key: MYSQL_PASSWORD
        fromService:
          type: mysql
          name: cookbook-db
          property: password
      - key: MYSQL_DATABASE
        fromService:
          type: mysql
          name: cookbook-db
          property: database
      - key: MYSQL_PORT
        fromService:
          type: mysql
          name: cookbook-db
          property: port
    dependencies:
      - cookbook-db

  - type: mysql
    name: cookbook-db
    plan: free
    region: oregon
    ipAllowList: []
    database: cookBook
    user: root
