services:
  - type: web
    name: cookbook
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: apache2-foreground
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/main
      - key: PHP_MEMORY_LIMIT
        value: 256M

  - type: mysql
    name: cookbook-db
    ipAllowList: []
    plan: free
    region: oregon
    database: cookBook
    user: cookbook_user
