services:
  - type: web
    name: cookbook
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: docker build -t cookbook . && docker run -p 80:80 cookbook
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/main
      - key: PHP_MEMORY_LIMIT
        value: 256M
      - key: DB_HOST
        value: mysql.render.com
      - key: DB_USER
        value: cookbook_user
      - key: DB_PASSWORD
        generateValue: true
      - key: DB_NAME
        value: cookbook_db
    healthCheckPath: /main/index.php
    autoDeploy: true

  - type: mysql
    name: cookbook-mysql
    region: oregon
    plan: free
    ipAllowList: []
    database: cookbook_db
    user: cookbook_user

databases:
  - name: cookbook-db
    databaseName: cookBook
    user: cookbook_user
    plan: free 